apiVersion: v1
kind: Service
metadata:
  name: bluesky-query-service
  namespace: bluesky-query
spec:
  selector:
    app: bluesky-query-service
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
  type: ClusterIP