apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: bluesky-query-service
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  project: default
  source:
    repoURL: https://github.com/g-clef/bluesky-query-layer
    targetRevision: HEAD
    path: kubernetes
    kustomize: {}
  destination:
    server: https://kubernetes.default.svc
    namespace: bluesky-query
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=false
    retry:
      limit: 3
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
  ignoreDifferences:
    - group: apps
      kind: Deployment
      jsonPointers:
        - /spec/replicas